---
title: "week5_exercise"
author: "Wenke Zimmermann"
date: "2022-05-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries ###
```{r message=FALSE, warning= FALSE}
library(readr)
library(udunits2)
library(sf)
library(terra)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tmap)

```

## Load data as an sf-object
```{r}

wildschwein <- read_delim("wildschwein_BE_2056.csv",",") %>%
  st_as_sf(coords = c("E", "N"), crs = 2056, remove = FALSE)

```


## Tasks 1: Import and visualize spatial data
```{r}

feldaufnahmen <- read_sf("Feldaufnahmen_Fanel.gpkg")

#What information does the dataset contain?
feldaufnahmen
#Geometrie: Polygon
#Projektion: Landeskoordinaten
#975 Zeilen, 3 Attribute
#...

#What is the geometry type of the dataset (possible types are: Point, Lines and Polygons)?
#Polygons

#What are the data types of the other columns?
#FieldID: double (Nummer des Feldes)
#geom: Koordinaten

#What is the coordinate system of the dataset?
#Landeskoordinaten

```


## Task 2: Annotate Trajectories from vector data
what crop was visited by which wild boar, and at what time
```{r}

#filter wildboar data to may to june (crop data is most relevant in summer), save output to new variable

#Anlegen convenience-Variable 'month'
wildschwein$month <- month(wildschwein$DatetimeUTC) #einfache Variante um convenience-Variable anzulegen

#alternativ mit mutate
#wildschwein %>%
#  mutate(month ???? )

#Filter auf Monate Mai und Juni
wildschwein_sommer <- wildschwein %>%
  filter(month == 05 | month == 06)

#folgende Variante ist viiiiieeeel zu umständlich
#wildschwein_sommer2015 <- wildschwein %>%
#  filter(DatetimeUTC >= as.POSIXct("2015-05-01", tz = "UTC") & DatetimeUTC <= #as.POSIXct("2015-06-30", tz = "UTC"))

#wildschein_summer2014 <- wildschwein %>%
#    filter(DatetimeUTC >= as.POSIXct("2014-05-01 ", tz = "UTC") & DatetimeUTC <= #as.POSIXct("2014-06-30", tz = "UTC"))



#Overlay the filtered dataset with your fanel data to verify the spatial overlap
#To sematically annotate wildboar locations with crop information, use a spatial join

wildschwein_overlay <- st_join(wildschwein_sommer, feldaufnahmen) 

```




